### ISSUE TITLE
After mounting, X endstop is not touching

### ISSUE THREAD

**Issue by nbouayad** [BondtechAB/Bondtech_Prusa_i3#27]
Hello,
On a Prusa MK2,the extruder rear cables prevent the x-endstop to be pushed, as seen in the attached pictures :

![PXL_20230917_124916043](https://github.com/BondtechAB/Bondtech_Prusa_i3/assets/7010735/e37eb377-5f4f-4ad4-906c-6bd6781440a1)

![PXL_20230917_124926517](https://github.com/BondtechAB/Bondtech_Prusa_i3/assets/7010735/eb748697-c03d-4b1b-b820-9b3d54766a35)

![PXL_20230917_124907172](https://github.com/BondtechAB/Bondtech_Prusa_i3/assets/7010735/3403ebb9-2efb-45d6-af8d-1cf303a3b501)
 
What can be done??!
Thanks,

**Comment by lejo1512** [comment]
I assume you are using "X-Carriage-modded(R2)__for_MK2(s)" with the extended arm to hit the switch?
Is the 

With the R3 cable-holder design the sleeve and zip-ties needs to be properly tightened around the cables.
The cable should be within the geometry of the cable-holder. 

You could try the MK2.5 version of the cable holder, gives some more space around the frame: 
https://github.com/prusa3d/Original-Prusa-i3/blob/MK2.5/Printed-Parts/stl/cable_holder.stl

![image](https://github.com/BondtechAB/Bondtech_Prusa_i3/assets/45564486/1ab3808f-d055-411a-88ba-7c016359e07e)
(From Prusa MK2.5 assembly guide)

**Comment by nbouayad-wincomplm** [comment]
@lejo1512, thank you for your answer.
Yes, I am using the modded R2 for MK2(s).
I will try the MK2.5 version of the cable holder and come back to you.
Kind regards,

**Comment by nbouayad** [comment]
@lejo1512, using the MK2.5 cable holder solved the situation!!
Thanks again!
