### ISSUE TITLE
Z_MAX_POS issue on MK2.5s

### ISSUE THREAD

**Issue by falconrh** [BondtechAB/Bondtech_Prusa_i3#8]
I am having a problem with the XYZ Calibration tests after installing the BondTech Extruder on my Prusa MK2.5s. The Extruder travels down to 5mm and stops. (~1mm above the bed)  When I looked at the Z_MAX_POS value in the source code (1_75mm_MK25S_Bondtech-RAMBo13a-E3Dv6full.h), I see that it is set to 210 not 205.  My understanding is the correct value is 205.

**Comment by lejo1512** [comment]
I've uploaded correct files now. 
Thanks for reporting this issue!

**Comment by falconrh** [comment]
Yes, that fixed my issues.  Thanks for the quick turnaround :)
